### ISSUE TITLE
function won't addClass to get image for card

### ISSUE THREAD

**Issue by w-dayrit** [w-dayrit/highlow#2]
dealCard() line77

I'm trying to addClass of the currentCard's img property. I want to show the currentCard's picture when I press the deal button.

The images and css are linked properly, because the backs of the cards are showing on the board.

**Comment by w-dayrit** [comment]
fixed image property. took off "."'s and added spaces to make function add the classes properly

**Comment by ghost** [comment]
Cool! Remember to assign one of us so that we are alerted when you post an issue! :)
